catching-non-exception:27:7::"Catching an exception which doesn't inherit from Exception: MyException":HIGH
catching-non-exception:33:7::"Catching an exception which doesn't inherit from Exception: MyException":HIGH
catching-non-exception:33:7::"Catching an exception which doesn't inherit from Exception: MySecondException":HIGH
catching-non-exception:54:7::"Catching an exception which doesn't inherit from Exception: None":HIGH
catching-non-exception:54:7::"Catching an exception which doesn't inherit from Exception: list()":HIGH
catching-non-exception:59:7::"Catching an exception which doesn't inherit from Exception: None":HIGH
catching-non-exception:72:7::"Catching an exception which doesn't inherit from Exception: 4":HIGH
catching-non-exception:72:7::"Catching an exception which doesn't inherit from Exception: None":HIGH
catching-non-exception:72:7::"Catching an exception which doesn't inherit from Exception: list([4, 5, 6])":HIGH
catching-non-exception:85:7::"Catching an exception which doesn't inherit from Exception: NON_EXCEPTION_TUPLE":HIGH
catching-non-exception:103:7::"Catching an exception which doesn't inherit from Exception: object":HIGH
catching-non-exception:108:7::"Catching an exception which doesn't inherit from Exception: range":HIGH
